#!/bin/bash
set -ex

docker image build \
    --build-arg VCS_REF="${GIT_SHA1}" \
    --build-arg SOURCE_REPOSITORY_URL="${SOURCE_REPOSITORY_URL}" \
    --build-arg GIT_TAG="${GIT_TAG}" \
    --build-arg BUILD_DATE="$(date --rfc-3339 ns)" \
    --tag ${IMAGE_NAME} \
    .
